# Create Inter Arrival Time

In [16]:
import pandas as pd
from google.colab import drive


drive.mount('/content/drive')

data = {
    "IAT": list(range(1, 9)),
    "Probability": [0.125] * 8,
}

df = pd.DataFrame(data)


df["Cumulative Probability"] = df["Probability"].cumsum()

df["Upper"] = (df["Cumulative Probability"] * 1000).astype(int)

file_path = "/content/drive/MyDrive/iat_table.csv"
df.to_csv(file_path, index=False)

print(df)
print("CSV file saved to Google Drive:", file_path)

df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   IAT  Probability  Cumulative Probability  Upper
0    1        0.125                   0.125    125
1    2        0.125                   0.250    250
2    3        0.125                   0.375    375
3    4        0.125                   0.500    500
4    5        0.125                   0.625    625
5    6        0.125                   0.750    750
6    7        0.125                   0.875    875
7    8        0.125                   1.000   1000
CSV file saved to Google Drive: /content/drive/MyDrive/iat_table.csv

   IAT  Probability  Cumulative Probability  Upper
0    1        0.125                   0.125    125
1    2        0.125                   0.250    250
2    3        0.125                   0.375    375
3    4        0.125                   0.500    500
4    5        0.125                   0.625    625
5    6        0.125                   0.750    750
6    7        0.125                   0.875    875
7    8        0.125                   1.000   1000

In [2]:
df

   IAT  Probability  Cumulative Probability  Upper
0    1        0.125                   0.125    125
1    2        0.125                   0.250    250
2    3        0.125                   0.375    375
3    4        0.125                   0.500    500
4    5        0.125                   0.625    625
5    6        0.125                   0.750    750
6    7        0.125                   0.875    875
7    8        0.125                   1.000   1000

# Create Service Time Table

In [3]:


data = {
    "Service Time": [1, 2, 3, 4, 5, 6],
    "Probability": [0.1, 0.2, 0.3, 0.25, 0.1, 0.05]
}

df = pd.DataFrame(data)

df["Cp"] = df["Probability"].cumsum()


df["Upper"] = (df["Cp"] * 100).astype(int)

df = df[["Service Time", "Probability", "Cp", "Upper"]]

file_path = "/content/drive/MyDrive/service_time_table.csv"
df.to_csv(file_path, index=False)

print(df)
print("CSV file successfully saved at:")
print(file_path)

   Service Time  Probability    Cp  Upper
0             1         0.10  0.10     10
1             2         0.20  0.30     30
2             3         0.30  0.60     60
3             4         0.25  0.85     85
4             5         0.10  0.95     95
5             6         0.05  1.00    100
CSV file successfully saved at:
/content/drive/MyDrive/service_time_table.csv

In [4]:
df

   Service Time  Probability    Cp  Upper
0             1         0.10  0.10     10
1             2         0.20  0.30     30
2             3         0.30  0.60     60
3             4         0.25  0.85     85
4             5         0.10  0.95     95
5             6         0.05  1.00    100

# Take 2 table as Input

In [5]:


# File paths
iat_path = "/content/drive/MyDrive/iat_table.csv"
service_path = "/content/drive/MyDrive/service_time_table.csv"

iat_df = pd.read_csv(iat_path)
service_df = pd.read_csv(service_path)

print("IAT Table:")
display(iat_df)

print("Service Time Table:")
display(service_df)

IAT Table:

   IAT  Probability  Cumulative Probability  Upper
0    1        0.125                   0.125    125
1    2        0.125                   0.250    250
2    3        0.125                   0.375    375
3    4        0.125                   0.500    500
4    5        0.125                   0.625    625
5    6        0.125                   0.750    750
6    7        0.125                   0.875    875
7    8        0.125                   1.000   1000

Service Time Table:

   Service Time  Probability    Cp  Upper
0             1         0.10  0.10     10
1             2         0.20  0.30     30
2             3         0.30  0.60     60
3             4         0.25  0.85     85
4             5         0.10  0.95     95
5             6         0.05  1.00    100

# Time Between Arrival

In [6]:
data = {
    "Customer no": [1, 2, 3, 4, 5, 6],
    "Random digit": [None, 161 ,658, 359,606,198]
}

cust_df = pd.DataFrame(data)

In [7]:
def determine_iat(random_digit, iat_table):
    if pd.isna(random_digit):
        return None

    for _, row in iat_table.iterrows():
        if random_digit <= row["Upper"]:
            return row["IAT"]

    return None

In [8]:
cust_df["Time Between Arrival"] = cust_df["Random digit"].apply(lambda x: determine_iat(x, iat_df))
iat_results_df = cust_df[["Customer no","Random digit", "Time Between Arrival"]]
display(iat_results_df)

   Customer no  Random digit  Time Between Arrival
0            1           NaN                   NaN
1            2         161.0                   2.0
2            3         658.0                   6.0
3            4         359.0                   3.0
4            5         606.0                   5.0
5            6         198.0                   2.0

# service between time

In [9]:
data = {
    "Customer no": [1, 2, 3, 4, 5, 6],
    "Random digit": [66,97,89,2,16,70]
}

cust_df = pd.DataFrame(data)

In [10]:
def determine_service(random_digit, service_time_table):
    for _, row in service_time_table.iterrows():
        if random_digit <= row["Upper"]:
            return row["Service Time"]
    return None

In [11]:
cust_df["Service Between Arrival"] = cust_df["Random digit"].apply(lambda x: determine_service(x, service_df))
service_results_df = cust_df[["Customer no","Random digit", "Service Between Arrival"]]
service_results_df = service_results_df.rename(columns={"Random digit": "Random digit (Service)"})
display(service_results_df)

   Customer no  Random digit (Service)  Service Between Arrival
0            1                      66                      4.0
1            2                      97                      6.0
2            3                      89                      5.0
3            4                       2                      1.0
4            5                      16                      2.0
5            6                      70                      4.0

# Simulation Table

In [12]:
simulation_table = pd.merge(
    iat_results_df,
    service_results_df[["Customer no", "Random digit (Service)", "Service Between Arrival"]],
    on="Customer no",
    how="left"
)

print("Merged Simulation Table:")
display(simulation_table)

Merged Simulation Table:

,Customer no,Random digit,Time Between Arrival,Random digit (Service),Service Between Arrival
0,1,NaN,NaN,66,4.0
1,2,161.0,2.0,97,6.0
2,3,658.0,6.0,89,5.0
3,4,359.0,3.0,2,1.0
4,5,606.0,5.0,16,2.0
5,6,198.0,2.0,70,4.0

In [13]:
import pandas as pd


cust_df = simulation_table.copy()
cust_df = cust_df.rename(columns={
    "Customer no": "Customer",
    "Time Between Arrival": "IAT",
    "Service Between Arrival": "ST"
})

# The first customer's IAT is typically 0
cust_df.loc[0, "IAT"] = 0

# Convert IAT and ST to integer type if they are float
cust_df["IAT"] = cust_df["IAT"].astype(int)
cust_df["ST"] = cust_df["ST"].astype(int)

cust_df["AT"] = 0
cust_df["TSB"] = 0
cust_df["TSE"] = 0
cust_df["WT"] = 0
cust_df["TTS"] = 0
cust_df["Idle Time"] = 0


for i in range(len(cust_df)):

    if i == 0:
        cust_df.loc[i, "AT"] = 0
    else:
        cust_df.loc[i, "AT"] = cust_df.loc[i-1, "AT"] + cust_df.loc[i, "IAT"]

    if i == 0:
        cust_df.loc[i, "TSB"] = 0
    else:
        cust_df.loc[i, "TSB"] = max(cust_df.loc[i, "AT"], cust_df.loc[i-1, "TSE"])

    cust_df.loc[i, "TSE"] = cust_df.loc[i, "TSB"] + cust_df.loc[i, "ST"]


    cust_df.loc[i, "WT"] = cust_df.loc[i, "TSB"] - cust_df.loc[i, "AT"]


    cust_df.loc[i, "TTS"] = cust_df.loc[i, "WT"] + cust_df.loc[i, "ST"]


    if i == 0:
        cust_df.loc[i, "Idle Time"] = cust_df.loc[i, "TSB"]
    else:
        cust_df.loc[i, "Idle Time"] = max(0, cust_df.loc[i, "TSB"] - cust_df.loc[i-1, "TSE"])


final_df = cust_df[["Customer","IAT","AT","ST","TSB","TSE","WT","TTS","Idle Time"]]
display(final_df)

   Customer  IAT  AT  ST  TSB  TSE  WT  TTS  Idle Time
0         1    0   0   4    0    4   0    4          0
1         2    2   2   6    4   10   2    8          0
2         3    6   8   5   10   15   2    7          0
3         4    3  11   1   15   16   4    5          0
4         5    5  16   2   16   18   0    2          0
5         6    2  18   4   18   22   0    4          0

In [18]:
final_df

   Customer  IAT  AT  ST  TSB  TSE  WT  TTS  Idle Time
0         1    0   0   4    0    4   0    4          0
1         2    2   2   6    4   10   2    8          0
2         3    6   8   5   10   15   2    7          0
3         4    3  11   1   15   16   4    5          0
4         5    5  16   2   16   18   0    2          0
5         6    2  18   4   18   22   0    4          0